name: Scrape and publish
run-name: Scrape and publish ${{ github.run_number }}
on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          version: "0.11.21"
          activate-environment: true

      - name: Scrape prices
        # different output than the default so it is not .gitignored (JamesIves/github-pages-deploy-action requires this)
        run: |
          uv run main.py --output remote-dist

      - name: Push prices to pp-hu-re-data
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: "remote-dist"
          token: ${{ secrets.DEPLOY_PAT }}
          commit-message: "Update prices from ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
          git-config-name: "Adam Reisinger"
          git-config-email: reisinger.adam@gmail.com
          repository-name: "Res42/pp-hu-re-data"
          branch: master
          clean-exclude: |
            README.md
            LICENSE
