name: Scrape and publish
run-name: Scrape and publish ${{ github.run_number }}
on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6

      - name: Checkout pp-hu-re-data repo
        uses: actions/checkout@v6
        with:
          repository: Res42/pp-hu-re-data
          path: dist
          persist-credentials: false

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          version: "0.11.21"

      - name: Scrape prices
        run: |
          uv run main.py

      - name: Push prices to pp-hu-re-data
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: "dist"
          token: ${{ secrets.DEPLOY_PAT }}
          commit-message: "Update prices from ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
          git-config-name: "Adam Reisinger"
          git-config-email: reisinger.adam@gmail.com
          repository-name: "Res42/pp-hu-re-data"
          branch: master
